#!/usr/bin/env bash
set -euo pipefail

CONTAINER_NAME=quay
IMAGE=quay.io/projectquay/quay:latest
CONFIG_DIR=./quay-config           # generated by the UI
VOLUME_NAME=quay-storage           # named volume for persistent storage

# sanity
[[ -d "$CONFIG_DIR" ]] || { echo "Missing $CONFIG_DIR (your config bundle)"; exit 1; }

# stop/remove existing container
if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
  echo "Stopping and removing existing container: $CONTAINER_NAME"
  docker stop "$CONTAINER_NAME" >/dev/null || true
  docker rm -f "$CONTAINER_NAME" >/dev/null || true
fi

# create volume if missing
if ! docker volume ls --format '{{.Name}}' | grep -qx "$VOLUME_NAME"; then
  echo "Creating volume: $VOLUME_NAME"
  docker volume create "$VOLUME_NAME" >/dev/null
fi

# run quay
echo "Starting Quay..."
docker run -d \
  --name "$CONTAINER_NAME" \
  --restart always \
  -p 80:8080 \
  -v "$CONFIG_DIR":/conf/stack:Z \
  -v "$VOLUME_NAME":/datastorage:Z \
  --health-cmd='curl -fs http://localhost:8080/health/instance' \
  --health-interval=30s \
  --health-retries=3 \
  --health-timeout=5s \
  --health-start-period=30s \
  "$IMAGE"


echo "Quay started: http://quayregistry.localhost"
echo "Persistent storage volume: $VOLUME_NAME"
